os: unstable

image: Visual Studio 2017

platform:
  - x64
  - x86

environment:
  matrix:
    - nodejs_version: 9

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> yarn.lock
  - app/node_modules -> app/yarn.lock

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  # Bonjour
  - choco install -y --no-progress --allow-empty-checksums bonjour
  # Install npm dependencies
  - yarn

test_script:
  # - yarn lint
  # - yarn test
  - yarn package-ci
  - yarn test-e2e
